### ISSUE TITLE
Regex trace - look-behind requires fixed-width pattern

### ISSUE THREAD

**Issue by supritha** [thinkwelltwd/device_detector#11]
Trying to use device-detector
from device_detector import DeviceDetector
ua = 'Mozilla/5.0 (Linux; Android 4.3; C5502 Build/10.4.1.B.0.101) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.136 Mobile Safari/537.36'
DeviceDetector(ua).parse() results in trace

Here is the stacktrace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/device_detector/device_detector.py", line 213, in parse
    self.parse_bot()
  File "/usr/local/lib/python3.6/site-packages/device_detector/device_detector.py", line 272, in parse_bot
    self.bot = Bot(self.user_agent).parse()
  File "/usr/local/lib/python3.6/site-packages/device_detector/parser/parser.py", line 89, in parse
    self._parse()
  File "/usr/local/lib/python3.6/site-packages/device_detector/parser/parser.py", line 73, in _parse
    for ua_data in self.regex_list:
  File "/usr/local/lib/python3.6/site-packages/device_detector/yaml_loader.py", line 69, in regex_list
    regex['regex'] = re.compile(BOUNDED_REGEX.format(regex['regex']), re.IGNORECASE)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 566, in compile
    code = _code(p, flags)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 551, in _code
    _compile(code, p.data, flags)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 146, in _compile
    _compile(code, p, (flags | add_flags) & ~del_flags)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 146, in _compile
    _compile(code, p, (flags | add_flags) & ~del_flags)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 187, in _compile
    _compile(code, av, flags)
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/sre_compile.py", line 160, in _compile
    raise error("look-behind requires fixed-width pattern")
sre_constants.error: look-behind requires fixed-width pattern

Issue with the library?

**Comment by thinkwelltwd** [comment]
I need to set regex to be a hard dependency.

`pip install regex`

**Comment by supritha** [comment]
Yes it works now. Since it was not part of requirements.txt assumed it is available by default in python3. Adding it in requirements.txt or as hard dependency will be helpful

Thanks for the quick reply @thinkwelltwd
