### ISSUE TITLE
Regexp error: look-behind requires fixed-width pattern

### ISSUE THREAD

**Issue by almarklein** [thinkwelltwd/device_detector#14]
On Windows 10, reproduced art both Python 3.6 and 3.7:

```py
>>> from device_detector import DeviceDetector
>>> ua = 'Mozilla/5.0 (Linux; Android 4.3; C5502 Build/10.4.1.B.0.101) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.136 Mobile Safari/537.36'
device = DeviceDetector(ua).parse()
>>> device = DeviceDetector(ua).parse()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "c:\pythons\python37\lib\site-packages\device_detector\device_detector.py", line 213, in parse
    self.parse_bot()
  File "c:\pythons\python37\lib\site-packages\device_detector\device_detector.py", line 272, in parse_bot
    self.bot = Bot(self.user_agent).parse()
  File "c:\pythons\python37\lib\site-packages\device_detector\parser\parser.py", line 89, in parse
    self._parse()
  File "c:\pythons\python37\lib\site-packages\device_detector\parser\parser.py", line 73, in _parse
    for ua_data in self.regex_list:
  File "c:\pythons\python37\lib\site-packages\device_detector\yaml_loader.py", line 69, in regex_list
    regex['regex'] = re.compile(BOUNDED_REGEX.format(regex['regex']), re.IGNORECASE)
  File "c:\pythons\python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "c:\pythons\python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "c:\pythons\python37\lib\sre_compile.py", line 768, in compile
    code = _code(p, flags)
  File "c:\pythons\python37\lib\sre_compile.py", line 607, in _code
    _compile(code, p.data, flags)
  File "c:\pythons\python37\lib\sre_compile.py", line 168, in _compile
    _compile(code, p, _combine_flags(flags, add_flags, del_flags))
  File "c:\pythons\python37\lib\sre_compile.py", line 209, in _compile
    _compile(code, av, flags)
  File "c:\pythons\python37\lib\sre_compile.py", line 182, in _compile
    raise error("look-behind requires fixed-width pattern")
re.error: look-behind requires fixed-width pattern
```

**Comment by almarklein** [comment]
Ah, duplicate of #10 and #11. Nevertheless, would be good to put on the front-page that `pip install regex` is needed. Or better yet, put it in the requirements.

**Comment by thinkwelltwd** [comment]
The next release will have an updated requirements.txt file
