### ISSUE TITLE
Regex issue while importing device_detector

### ISSUE THREAD

**Issue by AyeshW** [thinkwelltwd/device_detector#24]
When I try to `import device_detector`, I got the following error though I have installed regex.

`Traceback (most recent call last):
  File "/home/ayesh/PycharmProjects/LogParcer/venv/preProcessor.py", line 4, in <module>
    import device_detector
  File "/home/ayesh/PycharmProjects/LogParcer/venv/lib/python3.6/site-packages/device_detector/__init__.py", line 3, in <module>
    from .parser import *
  File "/home/ayesh/PycharmProjects/LogParcer/venv/lib/python3.6/site-packages/device_detector/parser/__init__.py", line 1, in <module>
    from .client import *
  File "/home/ayesh/PycharmProjects/LogParcer/venv/lib/python3.6/site-packages/device_detector/parser/client/__init__.py", line 1, in <module>
    from .base import *
  File "/home/ayesh/PycharmProjects/LogParcer/venv/lib/python3.6/site-packages/device_detector/parser/client/base.py", line 7, in <module>
    from ..parser import Parser
  File "/home/ayesh/PycharmProjects/LogParcer/venv/lib/python3.6/site-packages/device_detector/parser/parser.py", line 9, in <module>
    from .extractors import (
  File "/home/ayesh/PycharmProjects/LogParcer/venv/lib/python3.6/site-packages/device_detector/parser/extractors.py", line 9, in <module>
    APP_ID = re.compile(r'\b([a-z]{2,5}\.[\w\d\.\-]+)', re.IGNORECASE)
AttributeError: module 'regex' has no attribute 'compile'`

**Comment by thinkwelltwd** [comment]
Then you have a problem with your installation of the `regex` library or python env.

In your python shell, try to run the following lines:

```python
import regex as re
re.compile(r'\b([a-z]{2,5}\.[\w\d\.\-]+)', re.IGNORECASE)
```
When that works, `device_detector` will too.
